[project]
name = "streamlit-rev-recogn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.1",
    "streamlit>=1.48.0",
    "numpy>=1.24.0",
]
